package image

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// TestMakeColorPaletteMatchesSigplot compares MakeColorPalette output
// against reference palettes generated by sigplot's ColorMap.js.
// Reference data: testdata/sigplot_reference_palettes.json
func TestMakeColorPaletteMatchesSigplot(t *testing.T) {
	data, err := os.ReadFile("testdata/sigplot_reference_palettes.json")
	if err != nil {
		t.Fatalf("Failed to read reference data: %v", err)
	}

	var ref map[string]json.RawMessage
	if err := json.Unmarshal(data, &ref); err != nil {
		t.Fatalf("Failed to parse reference data: %v", err)
	}

	colormaps := []string{
		"Ramp Colormap",
		"Greyscale",
		"Color Wheel",
		"Spectrum",
		"calewhite",
		"HotDesat",
		"Sunset",
	}

	for _, name := range colormaps {
		t.Run(name, func(t *testing.T) {
			rawRef, ok := ref[name]
			if !ok {
				t.Skipf("No reference data for %s", name)
				return
			}

			var refColors [][3]int
			if err := json.Unmarshal(rawRef, &refColors); err != nil {
				t.Fatalf("Failed to parse reference colors: %v", err)
			}

			controlColors := GetColorControlPoints(name)
			palette := MakeColorPalette(controlColors, 500)

			if len(palette) != len(refColors) {
				t.Fatalf("Palette size mismatch: got %d, want %d", len(palette), len(refColors))
			}

			mismatches := 0
			for i, rc := range refColors {
				gr := int(math.Round(palette[i].Red))
				gg := int(math.Round(palette[i].Green))
				gb := int(math.Round(palette[i].Blue))

				// Allow ±1 for floating point rounding differences
				if abs(gr-rc[0]) > 1 || abs(gg-rc[1]) > 1 || abs(gb-rc[2]) > 1 {
					if mismatches < 10 {
						t.Errorf("Color[%d]: got rgb(%d,%d,%d), want rgb(%d,%d,%d)",
							i, gr, gg, gb, rc[0], rc[1], rc[2])
					}
					mismatches++
				}
			}
			if mismatches > 0 {
				t.Errorf("Total mismatches: %d out of %d colors", mismatches, len(refColors))
			}
		})
	}
}

// TestColorIndexMatchesSigplot verifies the color index calculation
// matches sigplot's getColorIndex (truncation, not rounding).
func TestColorIndexMatchesSigplot(t *testing.T) {
	data, err := os.ReadFile("testdata/sigplot_reference_palettes.json")
	if err != nil {
		t.Fatalf("Failed to read reference data: %v", err)
	}

	var ref map[string]json.RawMessage
	if err := json.Unmarshal(data, &ref); err != nil {
		t.Fatalf("Failed to parse reference data: %v", err)
	}

	var indexTests []struct {
		Value int    `json:"value"`
		Index int    `json:"index"`
		Color [3]int `json:"color"`
	}
	if err := json.Unmarshal(ref["_indexTests"], &indexTests); err != nil {
		t.Fatalf("Failed to parse index tests: %v", err)
	}

	numColors := 500
	zmin := 0.0
	zmax := 100.0
	fscale := float64(numColors) / (zmax - zmin)

	for _, tt := range indexTests {
		t.Run("", func(t *testing.T) {
			n := (float64(tt.Value) - zmin) * fscale
			ci := int(n)
			if ci > numColors-1 {
				ci = numColors - 1
			}
			if ci < 0 {
				ci = 0
			}

			if ci != tt.Index {
				t.Errorf("value=%d: got index %d, want %d", tt.Value, ci, tt.Index)
			}
		})
	}
}

func abs(x int) int {
	if x < 0 {
		return -x
	}
	return x
}
