server {
    listen 80;

    # Proxy SDS API requests
    location /sigplot/sds/ {
        proxy_pass http://sds:5055/sds/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Serve Ember UI (dev server)
    location /sigplot/ui/ {
        proxy_pass http://ember:4200/sigplot/ui/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Livereload websocket
    location /livereload {
        proxy_pass http://ember:4200/livereload;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
