server {
    listen 80;

    resolver 127.0.0.11 ipv6=off valid=30s;
    set $sds_upstream "sds:5055";

    location = / {
        return 302 /sigplot/ui/;
    }

    location = /sigplot/ui {
        return 301 /sigplot/ui/;
    }

    location = /sds {
        proxy_pass http://$sds_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /sds/ {
        proxy_pass http://$sds_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /sigplot/ui/ {
        proxy_pass http://$sds_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
